In [1]:
import pandas as pd

school_df = pd.read_json('./data/raw_json/rdb_schools.json')
school_df.head()
school_df = school_df.rename(columns = {'address': 'location'})

In [2]:
faq_df = pd.read_json('./data/raw_json/rdb_faqs.json')
faq_df.head()

,school_code,category,question,answer,faq_id
0,NYU,Admissions,What are the key deadlines for undergraduate a...,"For undergraduate admissions at NYU, the key d...",NYU_FAQ_1
1,NYU,Admissions,Is NYU test-optional?,"Yes, NYU is test-optional through the 2026-202...",NYU_FAQ_2
2,NYU,Financial Aid,Does NYU meet 100% of demonstrated financial n...,"Yes, NYU will meet 100% of demonstrated financ...",NYU_FAQ_3
3,NYU,International Applicants,What English proficiency exams does NYU accept...,Non-native speakers may need to submit scores ...,NYU_FAQ_4
4,NYU,Spring Admissions,What is the benefit of Spring Admission at NYU?,Spring Admission allows students to start thei...,NYU_FAQ_5

In [3]:
# !pip install mysql-connector-python

In [4]:
import mysql.connector

# -------------SQL 연결-----------------#
connection = mysql.connector.connect(
    host = 'localhost', # MySQL 서버 주소(iP)
    user = 'ohgiraffers', # 사용자 이름
    password = 'ohgiraffers', # 비밀번호
    database = 'universirydb' #사용할 DB 스키마
)
cursor = connection.cursor(buffered=True)
# -------------------------------------#
cursor.execute("SELECT DATABASE();")
print(cursor.fetchone())

('universirydb',)

In [5]:
faq_df = pd.merge(school_df,faq_df, on = 'school_code', how = 'inner')
faq_df

,school_code,name,country,location,category,question,answer,faq_id
0,NYU,New York University,USA,"New York, NY",Admissions,What are the key deadlines for undergraduate a...,"For undergraduate admissions at NYU, the key d...",NYU_FAQ_1
1,NYU,New York University,USA,"New York, NY",Admissions,Is NYU test-optional?,"Yes, NYU is test-optional through the 2026-202...",NYU_FAQ_2
2,NYU,New York University,USA,"New York, NY",Financial Aid,Does NYU meet 100% of demonstrated financial n...,"Yes, NYU will meet 100% of demonstrated financ...",NYU_FAQ_3
3,NYU,New York University,USA,"New York, NY",International Applicants,What English proficiency exams does NYU accept...,Non-native speakers may need to submit scores ...,NYU_FAQ_4
4,NYU,New York University,USA,"New York, NY",Spring Admissions,What is the benefit of Spring Admission at NYU?,Spring Admission allows students to start thei...,NYU_FAQ_5
5,USC,University of Southern California,United States,"Los Angeles, California",Dates and Deadlines,What are the important application deadlines f...,USC has the following key deadlines: Early Act...,USC_FAQ_1
6,USC,University of Southern California,United States,"Los Angeles, California",Admission Requirements,What is included in the application checklist ...,The application checklist for USC includes: Th...,USC_FAQ_2
7,USC,University of Southern California,United States,"Los Angeles, California",Application Process,Does USC accept home-schooled students differe...,"Yes, home-schooled students applying to USC mu...",USC_FAQ_3
8,USC,University of Southern California,United States,"Los Angeles, California",Financial Aid,Does USC offer need-based financial aid to int...,"No, USC does not provide need-based financial ...",USC_FAQ_4
9,USC,University of Southern California,United States,"Los Angeles, California",International Students,What are the English proficiency requirements ...,International applicants whose native language...,USC_FAQ_5
10,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,What required items do I need to send after I ...,"After submitting your application, you must en...",UIUC_FAQ_1
11,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,What percentage of applicants get admitted?,"The admission rate varies from year to year, r...",UIUC_FAQ_2
12,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,Is the ACT or SAT optional for all first-year ...,"Yes, the ACT and SAT are optional for first-ye...",UIUC_FAQ_3
13,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,How do I check my application status in myIllini?,You can check your application status by loggi...,UIUC_FAQ_4
14,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,What should I do if I have questions regarding...,"For visa-related questions, please refer to th...",UIUC_FAQ_5
15,Columbia,Columbia University,USA,"New York, NY",Applying,What is Columbia looking for when evaluating s...,"Columbia reviews applications holistically, co...",Columbia_FAQ_1
16,Columbia,Columbia University,USA,"New York, NY",Applying,How competitive is admission to Columbia?,Admission to Columbia is highly competitive du...,Columbia_FAQ_2
17,Columbia,Columbia University,USA,"New York, NY",Applying,Are there advisers for specific departmental m...,"Yes, Columbia provides academic advisers for e...",Columbia_FAQ_3
18,Columbia,Columbia University,USA,"New York, NY",Applying,Does Columbia allow students to double major?,"Yes, students at Columbia are allowed to doubl...",Columbia_FAQ_4
19,Columbia,Columbia University,USA,"New York, NY",Applying,What are your secondary/high school course req...,Applicants must demonstrate a strong academic ...,Columbia_FAQ_5
20,Columbia,Columbia University,USA,"New York, NY",Applying,"Is there a minimum test score, class rank or G...",Columbia does not set strict minimums for test...,Columbia_FAQ_6
21,Columbia,Columbia University,USA,"New York, NY",Applying,How large are Columbia's classes?,"Columbia classes vary in size, with many gradu...",Columbia_FAQ_7
22,Columbia,Columbia University,USA,"New York, NY",Applying,Is there a maximum number of students admitted...,"No, Columbia does not impose caps on admission...",Columbia_FAQ_8
23,Columbia,Columbia University,USA,"New York, NY",Applying,May I apply to both Columbia College and Colum...,"Yes, students may apply to both Columbia Colle...",Columbia_FAQ_9
24,Columbia,Columbia University,USA,"New York, NY",Applying,When do application decisions become available?,Application decisions are released through the...,Columbia_FAQ_10
25,Columbia,Columbia University,USA,"New York, NY",Applying,What if I need an application deadline extension?,Columbia generally adheres strictly to its dea...,Columbia_FAQ_11
26,Columbia,Columbia University,USA,"New York, NY",Applying,How can I take advantage of everything I want ...,"Columbia offers various resources, programs, a...",Columbia_FAQ_12
27,Columbia,Columbia University,USA,"New York, NY",Financial Aid,Does Columbia grant credit for college courses...,"Yes, Columbia grants credit for eligible colle...",Columbia_FAQ_13
28,Columbia,Columbia University,USA,"New York, NY",Financial Aid,Are students required to live on campus? Can I...,First-year students are required to live on ca...,Columbia_FAQ_14
29,Columbia,Columbia University,USA,"New York, NY",Financial Aid,What is Columbia’s policy on admissions interv...,Interviews are not part of the application pro...,Columbia_FAQ_15
30,Columbia,Columbia University,USA,"New York, NY",International and Undocumented Students,What are the English Proficiency Requirements ...,International applicants must demonstrate prof...,Columbia_FAQ_16
31,Columbia,Columbia University,USA,"New York, NY",International and Undocumented Students,What is Columbia's policy on financial aid for...,Columbia meets 100% of the demonstrated need f...,Columbia_FAQ_17
32,BU,Boston University,United States,"Boston, MA",application process,What is Boston University’s test policy?,Boston University will adopt a test optional p...,BU_FAQ_1
33,BU,Boston University,United States,"Boston, MA",admissions deadlines,What are the Early Decision deadlines for Bost...,The Early Decision application deadline is Nov...,BU_FAQ_2
34,BU,Boston University,United States,"Boston, MA",financial aid,What is the BU Promise?,The BU Promise guarantees that Boston Universi...,BU_FAQ_3
35,BU,Boston University,United States,"Boston, MA",first-year applicants,How do I apply as a first-year student?,You must submit either the Common Application ...,BU_FAQ_4
36,BU,Boston University,United States,"Boston, MA",international students,What do international applicants need to submit?,International applicants are required to submi...,BU_FAQ_5
37,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",Application Process,What is the selection process for first-year a...,"UC Berkeley uses a holistic review process, wh...",UCBerkeley_FAQ_1
38,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",Standardized Testing,Does UC Berkeley require standardized test sco...,"No, UC Berkeley is test-free and does not cons...",UCBerkeley_FAQ_2
39,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",International Students,What is required for international applicants?,International applicants must either require a...,UCBerkeley_FAQ_3
40,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",Financial Aid,What are the costs associated with attending U...,The cost of attendance includes tuition and fe...,UCBerkeley_FAQ_4
41,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",Letters of Recommendation,Are letters of recommendation required for the...,Letters of recommendation are not required but...,UCBerkeley_FAQ_5
42,UCSD,"University of California, San Diego",USA,"La Jolla, CA",Admissions,How do I apply to UC San Diego?,You can apply to UC San Diego by submitting th...,UCSD_FAQ_1
43,UCSD,"University of California, San Diego",USA,"La Jolla, CA",Academics & Majors,What majors are offered at UC San Diego?,UC San Diego offers a wide range of majors acr...,UCSD_FAQ_2
44,UCSD,"University of California, San Diego",USA,"La Jolla, CA",Cost & Financial Aid,How much does it cost to attend UC San Diego?,The cost of attendance varies by residency sta...,UCSD_FAQ_3
45,UCSD,"University of California, San Diego",USA,"La Jolla, CA",First-Year,What are A-G requirements?,A-G requirements are a series of college prepa...,UCSD_FAQ_4
46,UCSD,"University of California, San Diego",USA,"La Jolla, CA",International Students,What English proficiency tests are accepted fo...,International students must demonstrate Englis...,UCSD_FAQ_5
47,Purdue,Purdue University,USA,"West Lafayette, IN",Admissions,What is the application process for Purdue Uni...,"To apply to Purdue University, first-year stud...",Purdue_FAQ_1
48,Purdue,Purdue University,USA,"West Lafayette, IN",Admissions,What are the application deadlines for Purdue ...,The application deadline for Early Action is N...,Purdue_FAQ_2
49,Purdue,Purdue University,USA,"West Lafayette, IN",Admissions,What are the SAT/ACT requirements for Purdue U...,Purdue accepts both SAT and ACT scores without...,Purdue_FAQ_3
50,Purdue,Purdue University,USA,"West Lafayette, IN",International Students,What are the English proficiency requirements ...,International students whose primary language ...,Purdue_FAQ_4
51,Purdue,Purdue University,USA,"West Lafayette, IN",Tuition and Fees,What are the tuition and fee rates for 2025-2026?,Tuition rates vary based on the program of stu...,Purdue_FAQ_5
52,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",application,What is the application fee for Penn State?,The application fee for domestic students is $...,PennState_FAQ_1
53,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",admissions,What are the Early Action and Priority Admissi...,"The Early Action Deadline is November 1, and t...",PennState_FAQ_2
54,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",requirements,What are the minimum high school course requir...,"For a four-year degree, students must complete...",PennState_FAQ_3
55,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",international,What are the steps for international students ...,International students should research program...,PennState_FAQ_4
56,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",eligibility,What is the GPA range for the middle 50% of ad...,The middle 50% GPA for admitted students at Un...,PennState_FAQ_5

In [ ]:
# 2. 이제 다시 실행 (주의: cursor = cursor.execute() 라고 쓰면 안 됩니다!)
cursor.execute('SHOW TABLES')

# 3. 결과 출력
for table in cursor:
    print(table)
school_df_sql = """INSERT INTO school_info(school_name, country , location)  
                    VALUE (%s, %s, %s)"""
# for _, row in school_df.iterrows(): # 데이터프레임을 한줄씩 쓰는것
#     cursor.execute(school_df_sql, (
#         row['name'],
#         row['country'],
#         row['location']))
    
school_data = school_df[['name', 'country', 'location']].values.tolist()
cursor.executemany(school_df_sql, school_data)
connection.commit()

print("school 완료")

cursor.execute('SELECT * FROM school_info')
rows = cursor.fetchall()
school_id_map = {row[1]: row[0] for row in rows}
faq_df['school_id'] = faq_df['name'].map(school_id_map) # 이름으로 primary key 추가
faq_df.head()

('faq_info',)
('school_info',)
school 완료

,school_code,name,country,location,category,question,answer,faq_id,school_id
0,NYU,New York University,USA,"New York, NY",Admissions,What are the key deadlines for undergraduate a...,"For undergraduate admissions at NYU, the key d...",NYU_FAQ_1,101
1,NYU,New York University,USA,"New York, NY",Admissions,Is NYU test-optional?,"Yes, NYU is test-optional through the 2026-202...",NYU_FAQ_2,101
2,NYU,New York University,USA,"New York, NY",Financial Aid,Does NYU meet 100% of demonstrated financial n...,"Yes, NYU will meet 100% of demonstrated financ...",NYU_FAQ_3,101
3,NYU,New York University,USA,"New York, NY",International Applicants,What English proficiency exams does NYU accept...,Non-native speakers may need to submit scores ...,NYU_FAQ_4,101
4,NYU,New York University,USA,"New York, NY",Spring Admissions,What is the benefit of Spring Admission at NYU?,Spring Admission allows students to start thei...,NYU_FAQ_5,101
5,USC,University of Southern California,United States,"Los Angeles, California",Dates and Deadlines,What are the important application deadlines f...,USC has the following key deadlines: Early Act...,USC_FAQ_1,102
6,USC,University of Southern California,United States,"Los Angeles, California",Admission Requirements,What is included in the application checklist ...,The application checklist for USC includes: Th...,USC_FAQ_2,102
7,USC,University of Southern California,United States,"Los Angeles, California",Application Process,Does USC accept home-schooled students differe...,"Yes, home-schooled students applying to USC mu...",USC_FAQ_3,102
8,USC,University of Southern California,United States,"Los Angeles, California",Financial Aid,Does USC offer need-based financial aid to int...,"No, USC does not provide need-based financial ...",USC_FAQ_4,102
9,USC,University of Southern California,United States,"Los Angeles, California",International Students,What are the English proficiency requirements ...,International applicants whose native language...,USC_FAQ_5,102
10,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,What required items do I need to send after I ...,"After submitting your application, you must en...",UIUC_FAQ_1,103
11,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,What percentage of applicants get admitted?,"The admission rate varies from year to year, r...",UIUC_FAQ_2,103
12,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,Is the ACT or SAT optional for all first-year ...,"Yes, the ACT and SAT are optional for first-ye...",UIUC_FAQ_3,103
13,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,How do I check my application status in myIllini?,You can check your application status by loggi...,UIUC_FAQ_4,103
14,UIUC,University of Illinois Urbana-Champaign,United States,"Urbana, IL 61801",Applicant,What should I do if I have questions regarding...,"For visa-related questions, please refer to th...",UIUC_FAQ_5,103
15,Columbia,Columbia University,USA,"New York, NY",Applying,What is Columbia looking for when evaluating s...,"Columbia reviews applications holistically, co...",Columbia_FAQ_1,104
16,Columbia,Columbia University,USA,"New York, NY",Applying,How competitive is admission to Columbia?,Admission to Columbia is highly competitive du...,Columbia_FAQ_2,104
17,Columbia,Columbia University,USA,"New York, NY",Applying,Are there advisers for specific departmental m...,"Yes, Columbia provides academic advisers for e...",Columbia_FAQ_3,104
18,Columbia,Columbia University,USA,"New York, NY",Applying,Does Columbia allow students to double major?,"Yes, students at Columbia are allowed to doubl...",Columbia_FAQ_4,104
19,Columbia,Columbia University,USA,"New York, NY",Applying,What are your secondary/high school course req...,Applicants must demonstrate a strong academic ...,Columbia_FAQ_5,104
20,Columbia,Columbia University,USA,"New York, NY",Applying,"Is there a minimum test score, class rank or G...",Columbia does not set strict minimums for test...,Columbia_FAQ_6,104
21,Columbia,Columbia University,USA,"New York, NY",Applying,How large are Columbia's classes?,"Columbia classes vary in size, with many gradu...",Columbia_FAQ_7,104
22,Columbia,Columbia University,USA,"New York, NY",Applying,Is there a maximum number of students admitted...,"No, Columbia does not impose caps on admission...",Columbia_FAQ_8,104
23,Columbia,Columbia University,USA,"New York, NY",Applying,May I apply to both Columbia College and Colum...,"Yes, students may apply to both Columbia Colle...",Columbia_FAQ_9,104
24,Columbia,Columbia University,USA,"New York, NY",Applying,When do application decisions become available?,Application decisions are released through the...,Columbia_FAQ_10,104
25,Columbia,Columbia University,USA,"New York, NY",Applying,What if I need an application deadline extension?,Columbia generally adheres strictly to its dea...,Columbia_FAQ_11,104
26,Columbia,Columbia University,USA,"New York, NY",Applying,How can I take advantage of everything I want ...,"Columbia offers various resources, programs, a...",Columbia_FAQ_12,104
27,Columbia,Columbia University,USA,"New York, NY",Financial Aid,Does Columbia grant credit for college courses...,"Yes, Columbia grants credit for eligible colle...",Columbia_FAQ_13,104
28,Columbia,Columbia University,USA,"New York, NY",Financial Aid,Are students required to live on campus? Can I...,First-year students are required to live on ca...,Columbia_FAQ_14,104
29,Columbia,Columbia University,USA,"New York, NY",Financial Aid,What is Columbia’s policy on admissions interv...,Interviews are not part of the application pro...,Columbia_FAQ_15,104
30,Columbia,Columbia University,USA,"New York, NY",International and Undocumented Students,What are the English Proficiency Requirements ...,International applicants must demonstrate prof...,Columbia_FAQ_16,104
31,Columbia,Columbia University,USA,"New York, NY",International and Undocumented Students,What is Columbia's policy on financial aid for...,Columbia meets 100% of the demonstrated need f...,Columbia_FAQ_17,104
32,BU,Boston University,United States,"Boston, MA",application process,What is Boston University’s test policy?,Boston University will adopt a test optional p...,BU_FAQ_1,106
33,BU,Boston University,United States,"Boston, MA",admissions deadlines,What are the Early Decision deadlines for Bost...,The Early Decision application deadline is Nov...,BU_FAQ_2,106
34,BU,Boston University,United States,"Boston, MA",financial aid,What is the BU Promise?,The BU Promise guarantees that Boston Universi...,BU_FAQ_3,106
35,BU,Boston University,United States,"Boston, MA",first-year applicants,How do I apply as a first-year student?,You must submit either the Common Application ...,BU_FAQ_4,106
36,BU,Boston University,United States,"Boston, MA",international students,What do international applicants need to submit?,International applicants are required to submi...,BU_FAQ_5,106
37,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",Application Process,What is the selection process for first-year a...,"UC Berkeley uses a holistic review process, wh...",UCBerkeley_FAQ_1,107
38,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",Standardized Testing,Does UC Berkeley require standardized test sco...,"No, UC Berkeley is test-free and does not cons...",UCBerkeley_FAQ_2,107
39,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",International Students,What is required for international applicants?,International applicants must either require a...,UCBerkeley_FAQ_3,107
40,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",Financial Aid,What are the costs associated with attending U...,The cost of attendance includes tuition and fe...,UCBerkeley_FAQ_4,107
41,UCBerkeley,"University of California, Berkeley",USA,"Berkeley, CA",Letters of Recommendation,Are letters of recommendation required for the...,Letters of recommendation are not required but...,UCBerkeley_FAQ_5,107
42,UCSD,"University of California, San Diego",USA,"La Jolla, CA",Admissions,How do I apply to UC San Diego?,You can apply to UC San Diego by submitting th...,UCSD_FAQ_1,108
43,UCSD,"University of California, San Diego",USA,"La Jolla, CA",Academics & Majors,What majors are offered at UC San Diego?,UC San Diego offers a wide range of majors acr...,UCSD_FAQ_2,108
44,UCSD,"University of California, San Diego",USA,"La Jolla, CA",Cost & Financial Aid,How much does it cost to attend UC San Diego?,The cost of attendance varies by residency sta...,UCSD_FAQ_3,108
45,UCSD,"University of California, San Diego",USA,"La Jolla, CA",First-Year,What are A-G requirements?,A-G requirements are a series of college prepa...,UCSD_FAQ_4,108
46,UCSD,"University of California, San Diego",USA,"La Jolla, CA",International Students,What English proficiency tests are accepted fo...,International students must demonstrate Englis...,UCSD_FAQ_5,108
47,Purdue,Purdue University,USA,"West Lafayette, IN",Admissions,What is the application process for Purdue Uni...,"To apply to Purdue University, first-year stud...",Purdue_FAQ_1,109
48,Purdue,Purdue University,USA,"West Lafayette, IN",Admissions,What are the application deadlines for Purdue ...,The application deadline for Early Action is N...,Purdue_FAQ_2,109
49,Purdue,Purdue University,USA,"West Lafayette, IN",Admissions,What are the SAT/ACT requirements for Purdue U...,Purdue accepts both SAT and ACT scores without...,Purdue_FAQ_3,109
50,Purdue,Purdue University,USA,"West Lafayette, IN",International Students,What are the English proficiency requirements ...,International students whose primary language ...,Purdue_FAQ_4,109
51,Purdue,Purdue University,USA,"West Lafayette, IN",Tuition and Fees,What are the tuition and fee rates for 2025-2026?,Tuition rates vary based on the program of stu...,Purdue_FAQ_5,109
52,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",application,What is the application fee for Penn State?,The application fee for domestic students is $...,PennState_FAQ_1,110
53,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",admissions,What are the Early Action and Priority Admissi...,"The Early Action Deadline is November 1, and t...",PennState_FAQ_2,110
54,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",requirements,What are the minimum high school course requir...,"For a four-year degree, students must complete...",PennState_FAQ_3,110
55,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",international,What are the steps for international students ...,International students should research program...,PennState_FAQ_4,110
56,PennState,The Pennsylvania State University,USA,"201 Old Main, University Park, PA 16802",eligibility,What is the GPA range for the middle 50% of ad...,The middle 50% GPA for admitted students at Un...,PennState_FAQ_5,110

In [9]:
faq_df_sql = """INSERT INTO faq_info(school_id, question , answer, category)  
                    VALUE (%s, %s, %s, %s)"""

cols = ['school_id', 'question', 'answer', 'category']

faq_data = faq_df[cols] \
    .astype(object) \
    .where(pd.notnull(faq_df[cols]), None) \
    .values.tolist()

# 6️⃣ INSERT
cursor.executemany(faq_df_sql, faq_data)
connection.commit()

print("완료")

완료